# Generated by Django 5.2.8 on 2025-11-26 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_master_unit_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=100)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_quantity', models.IntegerField()),
                ('product_price', models.FloatField(null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.unit')),
            ],
        ),
    ]
